### ISSUE TITLE
Reading output data

### ISSUE THREAD

**Issue by hammadmazhar1** [naviga-tor/navigator#1]
Hi,
Im looking into NavigaTor as part of research, and am trying to do a run. The run goes perfectly fine, creates the probe data file, which is verifiable by testdata.py. Question is, how do I get the JSON data? The file is not accessible via tar or lzip.

**Comment by naviga-tor** [comment]
Right. IIRC, the script to convert measurement data to JSON is not available right now because it depends on some other scripts. I will look into how we can make them available.

**Comment by naviga-tor** [comment]
I just added a script (json_export.py) that converts NavigaTor measurements to JSON. It does not include the calculation of the Circuit-RTT, CBT, and congestion-aware metrics, however. If you need that, too, please let me know.

**Comment by hammadmazhar1** [comment]
If I could get that too, which would be great.

**Comment by naviga-tor** [comment]
I just uploaded the missing scripts (cat.py, r9.py) and updated json_export.py accordingly.
The website will be updated within the next minutes.
